apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
spec:
  template:
    spec:
      containers:
      - name: neuromorphic
        resources:
          limits:
            nvidia.com/gpu: 1
